[project]
name = "stacksone-vault"
description = "StacksOne Vault Ecosystem"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = [
    { contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard" }
]

[project.cache_location]
path = ".requirements"

# --- HANYA ADA 5 KONTRAK INI ---

[contracts.token-poin]
path = "contracts/token-poin.clar"
clarity_version = 2
epoch = 2.5

[contracts.token-one]
path = "contracts/token-one.clar"
clarity_version = 2
epoch = 2.5

[contracts.faucet-distributor]
path = "contracts/faucet-distributor.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["token-poin"]

[contracts.staking-refinery]
path = "contracts/staking-refinery.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["token-poin", "token-one"]

[contracts.utility-gacha]
path = "contracts/utility-gacha.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["token-poin", "token-one"]
