[project]
name = "stacksone-vault"
description = "StacksOne Vault Ecosystem"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = [
    { contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard" }
]

[project.cache_location]
path = ".requirements"

# HANYA SISAKAN INI
[contracts.genesis-core-v6]
path = "contracts/genesis-core-v6.clar"
clarity_version = 2
epoch = 2.5
