[project]
name = "stacksone-vault"
description = "StacksOne Vault Ecosystem"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = [
    { contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard" },
    { contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait" }
]

[project.cache_location]
path = ".requirements"

[contracts.mission-mini-001]
path = "contracts/mission-mini-001.clar"
clarity_version = 2
epoch = 2.5

[contracts.mission-mini-002]
path = "contracts/mission-mini-002.clar"
clarity_version = 2
epoch = 2.5

[contracts.mission-mini-003]
path = "contracts/mission-mini-003.clar"
clarity_version = 2
epoch = 2.5

[contracts.mission-mini-004]
path = "contracts/mission-mini-004.clar"
clarity_version = 2
epoch = 2.5

[contracts.mission-mini-005]
path = "contracts/mission-mini-005.clar"
clarity_version = 2
epoch = 2.5
